Proposal Feedback: Comparison of Splunk and Nagios Devop monitoring tools and their use cases
KTH/devops-course pull request #1178
Opened 2021-04-12 15:42 UTC by Renstrom

# Feedback Proposal: Comparison of Splunk and Nagios Devop monitoring tools and their use cases (#1021)

## Members

Yuxin Meng [@yuxinm](https://github.com/yuxinmmmm)
Anders Renström [@renstr](https://github.com/Renstrom)

## Proposal

Want to provide feedback for the above essay. [#1021](https://github.com/KTH/devops-course/pull/1021).

2021-04-13 13:32 UTC, khesoem requested changes

2021-04-13 13:32 UTC, khesoem commented on contributions/feedback/renstr-yuxinm/README.md
> +Anders Renström [@renstr](https://github.com/Renstrom)
Please write your full KTH email.

2021-04-13 13:33 UTC, khaes-kth commented
Please add a comment to #1021 and mention that you will give feedback on it.

2021-04-13 18:32 UTC, Renstrom commented on contributions/feedback/renstr-yuxinm/README.md
> +Anders Renström [@renstr](https://github.com/Renstrom)
Done

2021-04-14 10:57 UTC, merged

2021-04-24 11:25 UTC, carinawic commented
I have submitted the essay now as a PR and looking forward to receive your feedback!

The PR is number #1338

2021-04-28 14:32 UTC, carinawic commented
I have written a comment "Response to feedback" describing how we altered our report thanks to your feedback in #1338 . Thank you!