Eassy proposal: devops and agile
KTH/devops-course pull request #1910
Opened 2022-05-03 15:33 UTC by Linnea55

# Assignment Proposal

## Title

Working with DevOps and Agile together

## Names and KTH ID
  - Linnea Hagman (lhagm@kth.se)
 
## Deadline

Task 4

## Category

Essay

## Description

Planned headings (wording and order might change):

Introduction
What is Agile?
What is DevOps?
How do they complement each other (to get a better quality of service delivered)?
How can agile and devops be used successfully together?
What are the challenges of using Devops and agile together? 
Conclusion

2022-05-06 12:39 UTC, cesarsotovalero commented
Hi @Linnea55,
Thanks for submitting this proposal.
I don't think Agile practices are **comparable** to DevOps.
I suggest you to the essay on the **complementarity** of both practices.
Please update the description with more details regarding the essay planning (topic and sections).
I'll revise your PR once you update the README.

2022-05-06 12:48 UTC, cesarsotovalero requested changes

2022-05-06 12:48 UTC, cesarsotovalero commented on contributions/essay/lhagm/README.md
> +I will erite an essay about agile vs devops. What are the similarities and differences? Can they complement eachother? Should you prefer one over the other?
Elaborate more on the complementarity of Agile and DevOps practices. Include a Headline of the topics that you plan to cover in the essay.

2022-05-09 11:06 UTC, Linnea55 commented
Hi @cesarsotovalero,

yesterday I made some changes in the README.md file. Hopefully they are sufficient to merge this PR.

2022-05-10 10:02 UTC, cesarsotovalero approved these changes

2022-05-10 10:02 UTC, cesarsotovalero commented
Hi @Linnea55, LGTM. 
Good luck!

2022-05-10 10:02 UTC, merged