Presentation suggestion
KTH/devops-course pull request #927
Opened 2021-03-23 11:42 UTC by arxra

No decided topic, but we promise to make it interesting!

2021-03-23 13:55 UTC, arxra commented
We want to present on what monitoring is and why it matters when everything is automated.

2021-03-24 12:30 UTC, arxra commented
Asking for topic feedback from a "random" Ta: @cesarsotovalero

2021-03-24 12:46 UTC, cesarsotovalero commented
Hi @arxra, the scope of your presentation is too broad. 

Can you focus on one specific monitoring tool instead?

2021-03-24 12:47 UTC, cesarsotovalero requested changes

2021-03-24 12:47 UTC, cesarsotovalero commented on contributions/presentation/week2/aronber-fbjorkma/README.md
> +- How to act upon the feedback gained from the system?
The topic is too broad. Please focus on explaining this based on a real monitoring tool.

2021-03-25 10:10 UTC, fbjorkman commented
New focus on briefly explaining what monitoring is and then focus on the monitoring tool Prometheus. Is that a better scope?

2021-03-25 10:56 UTC, cesarsotovalero approved these changes

2021-03-25 10:58 UTC, cesarsotovalero approved these changes

2021-03-25 10:59 UTC, cesarsotovalero commented
Hi @fbjorkman.
LGTM. I'm merging your PR.
Good luck with the presentation!

2021-03-25 11:00 UTC, merged