course automation proposal
KTH/devops-course pull request #944
Opened 2021-03-23 12:40 UTC by Chen-Zidi

Course automation proposal: Checking link validity in the course github text descriptions eg. readme files

2021-03-23 13:30 UTC, cesarsotovalero commented
Hi @Chen-Zidi,

What your action will do when finding a broken link?

2021-03-23 19:36 UTC, Spycsh commented
Hi @cesarsotovalero,
after finding a broken link, our idea is:  
1. to create a github action and whenever there is a pull request, the action should automatically parse the children or descendant pages under the course website (https://github.com/KTH/devops-course) to find all the broken links
2. to show the detail information (time of when the action find the broken link, the corresponding commit log and who writes this dead link, using git blame maybe) of all the broken links in a list of one issue

We are still thinking whether the trigger event of above action is a pull request or a timeout, and whether we need to parse all the children pages or just the pages produced in the new pull request. Of course we should do some filtering of the valid files to parse (emphasis on README file, txt file).

2021-03-24 09:07 UTC, cesarsotovalero commented
Hi @Spycsh,

> whether we need to parse all the children pages or just the pages produced in the new pull request

Checking only the links introduced in the PR is enough.
Then the ideal would be closing the PR with a message explaining that one of the links is broken. The other option is opening an issue with explaining the problem (not ideal because probable the person who opened the PR will is not going to take action).

2021-03-24 09:08 UTC, cesarsotovalero requested changes

2021-03-24 09:08 UTC, cesarsotovalero commented on contributions/course-automation/zidi-sihan/README.md
> +TODO
Please update with the details of your proposed solution.

2021-03-24 16:25 UTC, cesarsotovalero approved these changes

2021-03-24 16:25 UTC, cesarsotovalero commented
@Chen-Zidi LGTM now.

2021-03-24 16:25 UTC, merged