Registration
KTH/devops-course pull request #968
Opened 2021-03-24 12:08 UTC by annsudo

2021-03-24 13:55 UTC, khaes-kth commented
Hi,
I think the topic is relevant. A little more detail is needed.

2021-03-24 14:00 UTC, annsudo commented
Hi,
Thank you for fast reply. Can we add details closer to the presentation, or do we need to add them asap in terms of geting the spot for week2?

2021-03-24 14:01 UTC, khaes-kth requested changes
A little more information should be provided in your proposal.

Also, please try remove the `.DS_Store` file

2021-03-24 14:01 UTC, khesoem commented on contributions/presentation/week2/annnik-carllei/README.md
> +During the presentation we will talk about the importance of DevSecOps throughout different stages of DevOps lifecycle.  We will discuss what are the current best practices in DevSecOps.
- a short statement (1-3 sentences) about the relevance and timeliness for testing and devops
- bullet outline of the presentation

Don't forget to add these two.

2021-03-24 14:02 UTC, khaes-kth commented
> Hi,
> Thank you for fast reply. Can we add details closer to the presentation, or do we need to add them asap in terms of geting the spot for week2?

To get your PR merged, you have to add the information. So, I guess you should do it ASAP to get the spot for week2.

2021-03-25 12:50 UTC, annsudo commented
Done!

2021-03-25 12:52 UTC, khaes-kth commented
Hi @annsudo 
I just found this PR from previous years:
[https://github.com/KTH/devops-course/pull/435](https://github.com/KTH/devops-course/pull/435)

I think your proposal is too close to that one. You can make your proposal more concrete to make it different from that one.

2021-03-25 16:08 UTC, annsudo commented
Hi, I looked through that topic and our topics are about different things. Our group is not talking about Kubernetes at all. I wonder what should we change?

2021-03-25 16:33 UTC, khaes-kth commented
You are right, their topic is more specific. But they also talk about DevSecOps and the fact that they discuss DevSecOps in context of Kubernetes makes their topic more concrete and therefore more interesting.

I think you can make your work different from theirs by focusing more the third section of your agenda "Secure CI/ CD Pipelines (+ some tools)" and discuss a specific tool their.

WDYT?

2021-03-25 16:44 UTC, annsudo commented
Thank you for the recommendation, have reformulated it now

2021-03-26 09:32 UTC, closed without merging

2021-03-26 13:49 UTC, annsudo commented
Hi again, we made new changes where we narrow topic more. 
Yet I pulled it as new request:Presentation week2 #1005