Demo proposal: Implementation of Docker to React Application
KTH/devops-course pull request #992
Opened 2021-03-25 12:53 UTC by George-Bassilious

2021-03-25 13:35 UTC, cesarsotovalero requested changes

2021-03-25 13:35 UTC, cesarsotovalero commented on contributions/demo/despinoy-gdba/README.md
> +The demo is relevant to teach people to use docker.
Your proposal doesn't fulfill the difficulty and originality criteria for a demo, see https://github.com/KTH/devops-course/blob/2021/grading-criteria.md#video-demos.
Can you refine it and make it more specific, eg. by dockerizing and deploying a React native application instead?

2021-03-25 17:12 UTC, George-Bassilious commented
We have done some modifications now to the proposal! hopefully we understood your comment correctly.

2021-03-26 10:49 UTC, cesarsotovalero approved these changes

2021-03-26 10:49 UTC, cesarsotovalero commented
@George-Bassilious LGTM now, I'm merging.

2021-03-26 10:50 UTC, cesarsotovalero approved these changes

2021-03-26 10:50 UTC, merged